### ISSUE TITLE
NameError: name 'AhrefsApi' is not defined

### ISSUE THREAD

**Issue by GefenPuravida** [spremotely/ahrefs_api_python#1]
Hi,

Thanks for making this available,
Im having trouble finding the proper import/from commands so im stuck behind a:

```
NameError: name 'AhrefsApi' is not defined
```

Would appreciate your assistance if it is possible.

Many thanks.

**Comment by saltyfireball** [comment]
Running into the same problem currently.

**Comment by saltyfireball** [comment]
if I replace the dashes with underscores in the folder name in my site-packages I can import this.
ahrefs-api-python to ahrefs_api_python

```sh
mv ahrefs-api-python ahrefs_api_python
```

Then this works

```python
from ahrefs_api_python import AhrefsApi
```

**Comment by spremotely** [comment]
Thanks for your responses! This problem was fixed.
